[package]
name = "seeed-tfmini"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-io = { version = "0.7.1", optional = true }
embedded-io-async = { version = "0.7.0", optional = true }

[features]
embedded-io = ["dep:embedded-io"]
embedded-io-async = ["dep:embedded-io-async"]
